<?php
$info = $this->getCardInfo();
if (!isset($info['name'])) {
    $info['name'] = '';
}
?>

<?php if(isset($info)): ?>
    <?php echo $this->__('Name on the Card: %s', $this->htmlEscape($info['name'])) ?><br />
    <?php echo $this->__('Credit Card Type: %s', $this->htmlEscape(ucwords($info['card_type']))) ?><br />
    <?php echo $this->__('Credit Card Number: xxxx-%s', $this->htmlEscape($info['card_number'])) ?><br />
    <?php echo $this->__('Expiration Date: %s', $this->htmlEscape($info['card_exp'])) ?>
<?php else: ?>
    <p><?php echo $this->__('There was a problem retriving the payment information') ?></p>
<?php endif; ?>