<?php /* @var $this SM_XPos_Block_Adminhtml_XPos_Receipt_Totals */ ?>

<div class="total-zone">
    <table>
        <tbody>
            <?php if(in_array('subtotal', $this->additionFieldsToDisplay)): ?>
                <tr>
                    <td><?php echo $this->helper('sales')->__('Subtotal') ?></td>
                    <td align="right"><strong><?php echo $this->getSubtotal(); ?></strong></td>
                </tr>
            <?php endif; ?>
            <?php if(in_array('discount', $this->additionFieldsToDisplay)): ?>
                <tr>
                    <td><?php echo $this->helper('sales')->__('Discount') ?></td>
                    <td align="right"><strong><?php echo $this->getDiscountAmount(); ?></strong></td>
                </tr>
            <?php endif; ?>

            <?php if($this->getGiftCards() != false) :?>
                <?php $cards = $this->getGiftCards(); ?>
                <?php foreach($cards as $_card): ?>
                    <tr>
                        <td><?php echo $this->helper('sales')->__('Gift Card') ?> (<?php echo $_card['c']; ?>)</td>
                        <td align="right"><strong>-<?php echo $this->getOrder()->formatPrice($_card['a']); ?></strong></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if(in_array('tax', $this->additionFieldsToDisplay)): ?>
                <tr>
                    <td><?php echo $this->helper('sales')->__('Taxes') ?></td>
                    <td align="right"><strong><?php echo $this->getTaxesAmount(); ?></strong></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><?php echo $this->helper('sales')->__('Shipping') ?></td>
                <td align="right"><strong><?php echo $this->getShippingAmount(); ?></strong></td>
            </tr>
            <?php if($this->getStoreCredit() != false): ?>
                <tr>
                    <td><?php echo $this->helper('sales')->__('GiftCards') ?></td>
                    <td align="right"><strong><?php echo $this->getGiftCardsAmount(); ?></strong></td>
                </tr>
            <?php endif; ?>
            <?php if($this->getStoreCredit() != false): ?>
                <tr>
                    <td><?php echo $this->helper('sales')->__('Store Credit') ?></td>
                    <td align="right"><strong><?php echo $this->getStoreCredit(); ?></strong></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><?php echo $this->helper('sales')->__('Total') ?></td>
                <td align="right"><strong><?php echo $this->getGrandTotal(); ?></strong></td>
            </tr>
            <tr>
                <td><?php echo $this->helper('sales')->__('Total Paid') ?></td>
                <td align="right"><strong><?php echo $this->getTotalPaidFromTransaction(); ?></strong></td>
            </tr>
            <?php if($this->getChange() != false): ?>
                <tr>
                    <td><?php echo $this->helper('sales')->__('Change') ?></td>
                    <td align="right"><strong><?php echo $this->getChange(); ?></strong></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
