<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Credit Cards') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?php echo $this->__('Credit Cards') ?></h2>
        </div>
        <?php echo $this->getChildHtml('card_grid') ?>
    </div>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?php echo $this->__('Add A New Card') ?></h2>
        </div>
        <?php echo $this->getChildHtml('card_form') ?>
    </div>
</div>
