<?php $_productCollection = $this->getLoadedProductCollection() ?>
<?php $item = $this->getActiveItem() ?>
<?php if (!$_productCollection->count()): ?>
    <div class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </div>
<?php else: ?>
    <div class="listing-type-grid catalog-listing">   
        <div>
            <?php echo $this->getChildHtml('item.filter') ?>
        </div>
        <div>
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <div class="grid">
            <ul class="products-grid products-grid--max-4-col">
                <?php $_collectionSize = $_productCollection->count() ?>
                <?php
                $i = 0;
                foreach ($_productCollection as $_product):
                    ?>
                    <?php
                    $product_name = $this->htmlEscape($_product->getName());
                    if (strlen($product_name) > 45)
                        $product_name = substr($product_name, 0, 45) . '...';
                    ?>
                    <li class="item">
                        <a href="<?php echo Mage::helper('bundlecreatorplus')->getItemOptionViewUrl($_product->getId()) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image">
                            <div class="image ui-corner-all"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170, 170); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></div>
                        </a>
                        <div class="product-info">
                            <h2 class="product-name">
                                <a href="<?php echo Mage::helper('bundlecreatorplus')->getItemOptionViewUrl($_product->getId()) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                                    <?php echo $product_name ?>                            
                                </a>
                            </h2>
                            <?php if($this->getPackageProduct()->getPriceType() == Mage::helper('bundlecreatorplus')->getPriceType('dynamic')): ?>
                                <?php $itemOption = Mage::helper('bundlecreatorplus')->getOptionByProductId($this->getActiveItem()->getId(), $_product->getId());?>
                                <?php if(is_numeric($itemOption->getOverridePrice())): ?>
                                    <div class="price-box">
                                        <span class="regular-price"><span class="price"><?php echo Mage::helper('core')->currency($itemOption->getOverridePrice(), true, false) ?></span></span>                                    
                                    </div>
                                <?php else: ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php endif ?>
                            <?php else: ?>
                                <?php $itemOption = Mage::helper('bundlecreatorplus')->getOptionByProductId($this->getActiveItem()->getId(), $_product->getId());?>
                                <div class="price-box">
                                    <span class="regular-price"><span class="price"><?php echo Mage::helper('core')->currency($this->getActiveItem()->getPrice() + $itemOption->getOverridePrice(), true, false) ?></span></span>                                    
                                </div>
                            <?php endif ?>
                            <div class="actions">
                                <?php if ($_product->isSaleable()): ?>
                                    <div class="add-to-cart">
                                        <button type="button" class="button" onclick="setLocation('<?php echo Mage::helper('bundlecreatorplus')->getPackageAddItemOptionUrl($_product->getId()) ?>')"><span><span><?php echo $item->getQty() > 1 ? $this->__('Add <b>%s</b> to Package', intval($item->getQty())) : $this->__('Add to Package') ?></span></span></button>
                                    </div>
                                <?php endif; ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
        <div>
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif; ?>