<?php /* @var $this SM_XPayment_Block_Info_XpaymentMultiple */ ?>
<?php
$arrayNotShow = array('method','enable','check_no','check_date','checks');
$emi = $this->getEmi();
$modelIayz = Mage::getModel('xpos/iayz');
/*$quoteId =$emi['checkNo'];
$xposCashAmount =$emi['xposcash'];
$xposCashAmount =$emi['xposcc'];*/
?>
<strong>Split Payment #<?php echo $emi['check_no']; ?>:</strong></br>
<!--Quote ID: --><?php //echo $quoteId; ?><!--</br>-->
<!--XPos CASH Amount: <?php /*echo $xposCashAmount; */?></br>
XPos CC Amount: <?php /*echo $xposCashAmount; */?></br>-->
<?php
 foreach ($emi as $k => $v){
 ?>
  <?php if (!in_array($k,$arrayNotShow)) echo ($modelIayz->getConfigDataPaymentMethod($k,"title")) . ': ' . floatval($v) . '</br>'; ?>
 <?php
 }
 ?>
