<!------------------------>
<!-- Header -->
<div class="headerTag" id="homeHeaderTag">
	<div class="tagTitle">Baie-Saint-Paul<br>-<br>La Malbaie <br></div>
	<img class="tagLine" src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/ligneTitre.gif" />
	<div class="tagPriceContainer">
		<div class="tagPrice">39&nbsp;&nbsp;</div>
		<div class="tagAss">*</div>
		<div class="tagCent">.95</div>
		<div class="tagDollar">$</div>
	</div>
	<div class="tagTxs">* Taxes en sus.</div>
	<div class="rsBtn"><a href="#">Info</a></div>
</div>
<br/><br/><br/>
<!------------------------>
<!-- Header -->
<div id="homeReserv">
	<div id="homeReservMap"><img src="http://74.115.206.247/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/MapTrainWeb.png" /></div>
	<div id="homeReservWidget"><?php  echo  $this->getLayout()->createBlock('customwidget/bookingwidget')->setTemplate('customwidget/booking.phtml')->setBlockId('bookside')->toHtml()?></div>
	<div style="clear: both;"></div>
</div>
<br/>
<!------------------------>
<!-- Experience -->
<div class="featHomeCanvas">
	<div class="featHome" id="featExp">
		<div class="featOverlay">
			<div class="featTitle">Une expérience<BR/>unique</div>
			<img src="http://74.115.206.247/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/ligneBlanche.png" />
			<p>
				Embarquement immédiat vers les grands espaces. Un voyage à fleur d’eau et à flanc de montagnes. Pour voir grand. Loin. Autrement.
		 	</p>
		 	<br/>
		 	<div class="rsBtnInv"><a href="http://74.115.206.247/temp/magento/index.php/francais/l-experience-train.html">Info</a></div>
		</div>
	</div>
</div>
<!------------------------>
<!-- Destination -->
<div class="txtHome">
	<div class="txtHomeTitle">Quoi faire à destination</div>
	<img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/ligneTitre.gif" />
	<br/><br/>
	<p>
		D'un village côtier à l’autre, il y a tant à faire dans Charlevoix. De l’aventure douce à extrême, par où commencer ?
	 </p>
	 <br/><br/><br/>
</div>
<div class="destiHome">
	<div class="destiHomeCol">
		<div class="destiHomePic" style=""><img src="http://74.115.206.247/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/homeTaxi.jpg" /></div>
		<div class="destiHomeTitle"><br/>Baie-Saint-Paul</div>
		<div class="rsBtn"><a href="#">En savoir +</a></div>
	</div>
	<div class="destiHomeCol">
		<div class="destiHomePic"><img src="http://74.115.206.247/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/homeKayak.jpg" /></div>
		<div class="destiHomeTitle"><br/>La Malbaie</div>
		<div class="rsBtn"><a href="#">En savoir +</a></div>
	</div>
	<div class="destiHomeCol">
		<div class="destiHomePic"><img src="http://74.115.206.247/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/homeExpo.jpg" /></div>
		<div class="destiHomeTitle">Autres<br/>villages côtiers</div>
		<div class="rsBtn"><a href="#">En savoir +</a></div>
	</div>
	<div style="clear:both;"></div>
</div>

<br/><br/>
<!------------------------>
<!-- Hebergement -->
<div class="featHome" id="featHebergement">
	<div class="featOverlay">
		<div class="featTitle">Hébergement</div>
		<img src="http://74.115.206.247/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/ligneBlanche.png" />
		<p>
			Passer la nuit à destination? Quelle bonne idée! Plusieurs forfaits disponibles chez les hôteliers participants
	 	</p>
	 	<br/>
	 	<div class="rsBtnInv"><a href="http://74.115.206.247/temp/magento/index.php/francais/forfaits-hebergement.html">Info</a></div>
	</div>
</div>
<div class="featHome" id="featHotel2">
	<div id="featHotel">
		<div id="featHotelContainer">
			<div class="hotelCol">
				<div class="hotelNum">/01</div>
				<div class="hotelName">Hôtel Germain<br/>Charlevoix</div>
				<div class="rsBtnInv"><a href="#">En savoir +</a></div>
			</div>
			<div class="hotelCol">
				<div class="hotelNum">/02</div>
				<div class="hotelName">Auberge<br/>la Muse</div>
				<div class="rsBtnInv"><a href="#">En savoir +</a></div>
			</div>
			<div class="hotelCol hotelColNoBorder">
				<div class="hotelNum">/03</div>
				<div class="hotelName">Auberge<br/>des Falaises</div>
				<div class="rsBtnInv"><a href="#">En savoir +</a></div>
			</div>
			<div style="clear:both;"></div>
		</div>
	</div>
</div>


<br/><br/><br/><br/>

<div class='embed-container'><iframe src='https://www.youtube.com/embed/t1oxRAT5-7o' frameborder='0' allowfullscreen></iframe></div>


<div class="txtHome">
	<div class="txtHomeTitle">Partenaires</div>
	<img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/rc/ligneTitre.gif" />
	<br/>
	<div id="partnaires-list">
		 <ul>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/massif.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/bsp.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/tourismecharlevoix.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/goq.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/beaupre.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/malbaie.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/goc.gif" /></a></li>
		    <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/VDQ_nb.gif" /></a></li>
		     <li><img src="/temp/magento/skin/frontend/templatemela/MAG100210_default/images/partenaires/saint-irenee.gif" /></a></li>
		    
	  	</ul>
	</div>
</div>

<script>
    (function($){
        $(window).load(function(){
            $("#partnaires-list").mThumbnailScroller({
              axis:"x",
              type:"click-50",
              theme:"buttons-out"
            });
        });
    })(jQuery);
</script>

