<script type="text/javascript">
    optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
?>
<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="ajax_product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
    </div>
    <div id="product-shop">
        <div class="product-options" id="product-options-wrapper" style="margin:0">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
            <?php $_associatedProducts = $this->getAssociatedProducts() ?>
            <?php echo $this->getChildHtml('product_type_data_extra') ?>
            <table class="data-table grouped-items-table" id="super-product-table">
                <col />
                <col />
                <col width="1" />
                <thead>
                    <tr>
                        <th><?php echo $this->__('Product Name') ?></th>
                        <th class="a-right"><?php echo $this->__('Price') ?></th>
                        <?php if ($_product->isSaleable()): ?>
                            <th class="a-center"><?php echo $this->__('Qty') ?></th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($_associatedProducts)): ?>
                        <?php foreach ($_associatedProducts as $_item): ?>
                            <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
                            <tr>
                                <td><?php echo $this->htmlEscape($_item->getName()) ?></td>
                                <td class="a-right">
                                    <?php echo $this->getPriceHtml($_item, true) ?>
                                    <?php echo $this->getTierPriceHtml($_item) ?>
                                </td>
                                <?php if ($_product->isSaleable()): ?>
                                    <td class="a-center">
                                        <?php if ($_item->isSaleable()) : ?>
                                            <input type="text" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>

                    <?php else: ?>
                        <tr>
                            <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
            <div class="product-options-bottom">
                <?php echo $this->getChildHtml('addtocart'); ?>
            </div>
            <script type="text/javascript">decorateTable('super-product-table')</script>				
        </div>
    </div>

</form>
