<?php

?>
<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $helper = Mage::helper('bookme') ?>
<tr>
    <td class="label"><?php echo $helper->__($this->getElement()->getLabel()) ?></td>
    <td colspan="10" class="grid">
    <table cellspacing="0" class="data border" id="reminder_table">
        
        <col width="180" />
        <col width="180" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('bookme')->__('Time interval') ?></th>
                <th><?php echo Mage::helper('bookme')->__('Email Template') ?></th>
                <th class="last"><?php echo Mage::helper('bookme')->__('Action') ?></th>
            </tr>
        </thead>
        <tbody id="<?php echo $_htmlId ?>_container"></tbody>
        <tfoot>
            <tr>
                <td colspan="6" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
    </table>
<script type="text/javascript">// <![CDATA[

var reminder_template = 
	'<tr>'+
	'<td><select id="mail_reminder_{{index}}_period" name="<?php echo $_htmlName ?>[{{index}}][period]">'+
	'<option value="0"><?php echo $helper->__('immediate after payment') ?></option>'+
	'<option value="1"><?php echo $helper->__('1 hour') ?></option>'+
	'<option value="2"><?php echo $helper->__('2 hours') ?></option>'+
	'<option value="12"><?php echo $helper->__('12 hours') ?></option>'+
	'<option value="24"><?php echo $helper->__('24 hours') ?></option>'+
	'<option value="48"><?php echo $helper->__('two days') ?></option>'+
	'<option value="120"><?php echo $helper->__('five days') ?></option>'+
	'<option value="168"><?php echo $helper->__('one week') ?></option>'+
	'</select>'+
	'<input type="hidden" id="mail_reminder_{{index}}_deleted" name="<?php echo $_htmlName ?>[{{index}}][deleted]" value="{{deleted}}"/>'+
	'<input type="hidden" id="mail_reminder_{{index}}_reminder_id" name="<?php echo $_htmlName ?>[{{index}}][reminder_id]" value="{{reminder_id}}"/>'+
	'</td>'+
	'<td><select id="mail_reminder_{{index}}_email_id" name="<?php echo $_htmlName ?>[{{index}}][email_id]">'+
	<?php foreach ($this->getMailTemplates() as $template): ?>
		'<option value="<?php echo $template['value'] ?>"><?php echo $template['label'] ?></option>'+
	<?php endforeach;?>
	'</select></td>'+
	'<td><button title="remove" type="button" class="scalable delete icon-btn delete-product-option" '+
	'id="mail_reminder_{{index}}_delete_button" onclick="return reminders.remove(event, {{index}});" >'+
	'<span>Remove</span></button></td>'+	
	'</tr>';


	var reminders = {
		    tbody : $('<?php echo $_htmlId ?>_container'),
		    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
		    templateText : reminder_template,
		    itemCount : 0,
		    add : function() {
		        alertAlreadyDisplayed = false;
		        this.template = new Template(this.templateText, this.templateSyntax);

		        var data = {
				        reminder_id: '',
		                index: this.itemCount++
		            };
				
	            if(arguments.length == 3){
					data.reminder_id = arguments[0];
					data.email_id = arguments[1];
					data.period = arguments[2];
		        }
				
		        data.id = this.itemCount;
		        
		        Element.insert(this.tbody, {'bottom':this.template.evaluate(data)});
		        this.bindRemoveButtons();

				if(arguments.length == 3){
					$('mail_reminder_'+data.index+'_email_id').value = data.email_id;
					$('mail_reminder_'+data.index+'_period').value = data.period;
				}
		    },
		    remove : function(event){
			    var index = arguments[1];
		        var element = $(Event.findElement(event, 'tr'));
		        alertAlreadyDisplayed = false;
		        if(element){
		            $('mail_reminder_'+index+'_deleted').value = 1;
		            Element.select(element, 'div.flex').each(function(elm){
		                elm.remove();
		            });
		            element.addClassName('no-display');
		            element.addClassName('ignore-validate');
		            element.hide();
		        }
		    },
		    bindRemoveButtons : function(){
		        var buttons = $$('tbody#link_items_body .delete-link-item');
		        for(var i=0;i<buttons.length;i++){
		            if(!$(buttons[i]).binded && !$(buttons[i]).hasClassName('disabled')){
		                $(buttons[i]).binded = true;
		                Event.observe(buttons[i], 'click', this.remove.bind(this));
		            }
		        }
		    }
		    
		};



	reminders.bindRemoveButtons();
	<?php foreach ($this->getValues() as $item):?>
		
	reminders.add(
				'<?php echo $item['reminder_id']?>',
				 '<?php echo $item['email_id'] ?>',
				  '<?php echo $item['period'] ?>');
	<?php endforeach;?>
// ]]></script>
	</td>
</tr>