<?php
/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 6/24/15
 * Time: 2:19 PM
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<!--<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">-->
<meta name="HandheldFriendly" content="true">

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<title><?php /*echo htmlspecialchars(html_entity_decode($this->getTitle())) */?></title>
<title>X-POS</title>
<!--<link rel="icon" href="--><?php //echo $this->getSkinUrl('favicon.ico') ?><!--" type="image/x-icon"/>z-->
<!--<link rel="shortcut icon" href="--><?php //echo $this->getSkinUrl('favicon.ico') ?><!--" type="image/x-icon"/>-->

<?php echo $this->getCssJsHtml() ?>
<?php //echo $this->helper('core/js')->getTranslatorScript() ?>
<?php //echo $this->getChildHtml('calendar'); ?>
<?php //echo $this->getChildHtml('optional_zip_countries'); ?>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*', array('_nosid' => true)) ?>';
    var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
    var FORM_KEY = '<?php echo $this->getFormKey() ?>';

//    var countAllProductsUrl = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/xposproduct/countAll", array('_nosid' => true)); ?>//';

//    var loadProductUrl = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/xposproduct/load", array('_nosid' => true)); ?>//';
//    var xPosCheckProductUrl = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/xposproduct/checkNew", array('_nosid' => true)); ?>//';
//    var searchProductUrl = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/xposproduct/search", array('_nosid' => true)); ?>//';
//    var placeholder = '<img src = "<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/base/default/images/catalog/product/placeholder/small_image.jpg"; ?>//">';
//    var flag_reload_page = 0;
//    var productData = {};
//    var origProductData = {};
//    var categoryData = {};
//    var currentOrder = {};

//    var offlineSearch = <?php //echo Mage::getStoreConfig('xpos/search/offlinesearch') ?>// ==1;
//    var offlineSearch_customer = <?php //echo Mage::helper('xpos/configXPOS')->getOfflineSearchCustomer() ?>// ==1;

//    window.ON_FLY_DISCOUNT = <?php //echo Mage::getStoreConfig('xpos/general/onfly_discount'); ?>// == 1;

//    window.PRICE_FORMAT = <?php //echo Mage::helper('core')->jsonEncode(Mage::app()->getLocale()->getJsPriceFormat()) ?>//;
//    window.INCLUDE_TAX = <?php //echo Mage::getStoreConfig('tax/calculation/price_includes_tax'); ?>//;

//    window.CATALOG_PRICE_DISPLAY_TYPE = <?php //echo Mage::getStoreConfig('tax/display/type') ?>//;
//    window.SHOPPING_CART_PRICE_DISPLAY_TYPE = <?php //echo Mage::getStoreConfig('tax/cart_display/price') ?>//;
//    window.SHOPPING_CART_SUBTOTAL_DISPLAY_TYPE = <?php //echo Mage::getStoreConfig('tax/cart_display/subtotal') ?>//;
//    window.SHOPPING_CART_GRANDTOTAL_DISPLAY_TYPE = <?php //echo Mage::getStoreConfig('tax/cart_display/grandtotal') ?>//;
</script>

