<?php $_product = $this->getProduct() ?>
<?php $isAjax = $this->getIsAjax() ?>
<?php 
    if($isAjax) {
        $productFormId = 'ajax_product_addtocart_form';
        $productForm = 'ajaxProductAddToCartForm';
    } else {
        $productForm = 'packageProductAddToCartForm';
        $productFormId = 'product_addtocart_form';
    }
?>

<?php if ($_product->isSaleable()): ?>
    <?php $item = Mage::helper('bundlecreatorplus')->getPackageSession()->getActiveItem() ?>
    <div class="add-to-cart">
        <?php if(!$isAjax): ?><button type="button" class="button" onclick="history.go(-1);" style="margin-right: 5px"><span><span><?php echo $this->__('Go Back') ?></span></span></button><?php endif ?>
        <button type="button" class="button" onclick="$('<?php echo $productFormId ?>').action = '<?php echo Mage::helper('bundlecreatorplus')->getPackageAddItemOptionUrl($_product->getId()) ?>';<?php echo $productForm?>.submit()"><span><span><?php echo $item->getQty() > 1 ? $this->__('Add <b>%s</b> to Package', intval($item->getQty())) : $this->__('Add to Package') ?></span></span></button>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var packageProductAddToCartForm = new VarienForm('<?php echo $productFormId ?>');
        packageProductAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(packageProductAddToCartForm);
    //]]>
    </script>
<?php endif; ?>