<?php

?>
<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $helper = Mage::helper('bookme') ?>
<tr>
    <td class="label"><?php echo $helper->__($this->getElement()->getLabel()) ?></td>
    <td colspan="10" class="grid">
    <table cellspacing="0" class="data border" id="pricerule_table">
        <col width="180" />
        <col width="50" />
        <col width="50" />
        <col width="50" />
        <col width="50" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('bookme')->__('Name') ?></th>
                <th><?php echo Mage::helper('bookme')->__('Price Move') ?></th>
                <th><?php echo Mage::helper('bookme')->__('Amount Type') ?></th>
                <th><?php echo Mage::helper('bookme')->__('Amount') ?></th>
                <th class="last"><?php echo Mage::helper('bookme')->__('Action') ?></th>
            </tr>
        </thead>
        <tbody id="<?php echo $_htmlId ?>_container"></tbody>
        <tfoot>
            <tr>
                <td colspan="6" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
    </table>
<script type="text/javascript">// <![CDATA[

var price_profile_Template = 
	'<tr>'+
	'<td>'+
	'<table style="border:none" cellpadding="0" cellspacing="0"><td style="border:none">Admin: <input type="text" id="price_profile_{{index}}_name" name="<?php echo $_htmlName ?>[{{index}}][name]" value="{{name}}"/></td>'+
	<?php foreach ($this->getStoreData() as $store): ?>
		'<td style="border:none"><?php echo $store['name'] ?>:</td><td style="border:none"><input type="text" id="price_profile_{{index}}_<?php echo $store['code'] ?>" name="<?php echo $_htmlName ?>[{{index}}][<?php echo $store['code'] ?>]" value="{{<?php echo $store['code'] ?>}}"/></td></tr><tr><td style="border:none"></td>'+
	<?php endforeach;?>
	'</tr></table>'+
	'<input type="hidden" id="price_profile_{{index}}_deleted" name="<?php echo $_htmlName ?>[{{index}}][deleted]" value="{{deleted}}"/>'+
	'<input type="hidden" id="price_profile_{{index}}_profile_id" name="<?php echo $_htmlName ?>[{{index}}][profile_id]" value="{{profile_id}}"/>'+
	'</td>'+
	'<td><select id="price_profile_{{index}}_move" name="<?php echo $_htmlName ?>[{{index}}][move]">'+
	'<option value="1"><?php echo $helper->__('increase') ?></option><option value="2"><?php echo $helper->__('decrease') ?></option>'+
	'</select>'+
	'</td>'+
	'<td><select id="price_profile_{{index}}_amount_type" name="<?php echo $_htmlName ?>[{{index}}][amount_type]">'+
	'<option value="1"><?php echo $helper->__('percentage') ?></option><option value="2"><?php echo $helper->__('fixed amount') ?></option></select>'+
	'</td>'+
	'<td><input style="width:50px" type="text" id="price_profile_{{index}}_amount" name="<?php echo $_htmlName ?>[{{index}}][amount]" value="{{amount}}" />'+
	'</td>'+
	'<td><button title="remove" type="button" class="scalable delete icon-btn delete-product-option" '+
	'id="price_profile_{{index}}_delete_button" onclick="return profileItems.remove(event, {{index}});" >'+
	'<span>Remove</span></button></td>'+	
	'</tr>';


	var profileItems = {
		    tbody : $('<?php echo $_htmlId ?>_container'),
		    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
		    templateText : price_profile_Template,
		    itemCount : 0,
		    add : function() {
		        alertAlreadyDisplayed = false;
		        this.template = new Template(this.templateText, this.templateSyntax);

		        var data = {
				        profile_id: '',
		                index: this.itemCount++
		            };
				var i = 0;
				
	            if(arguments.length == 6){
					data.profile_id = arguments[0];
					data.name = arguments[1];
					data.amount = arguments[2];
					data.amount_type = arguments[3];
					data.move = arguments[4];
		        }

	            for (var key in arguments[5]) {
					  if (arguments[5].hasOwnProperty(key)) {
					    data[key] = arguments[5][key];
					 }
				}
				
		        data.id = this.itemCount;
		        
		        Element.insert(this.tbody, {'bottom':this.template.evaluate(data)});
		        this.bindRemoveButtons();

				if(arguments.length == 6){
					$('price_profile_'+data.index+'_move').value = data.move;
					$('price_profile_'+data.index+'_amount_type').value = data.amount_type;
				}else{
					this.addCondition(data.index, 1);
				}
		    },
		    remove : function(event){
			    var index = arguments[1];
		        var element = $(Event.findElement(event, 'tr'));
		        alertAlreadyDisplayed = false;
		        if(element){
		            $('price_profile_'+index+'_deleted').value = 1;
		            Element.select(element, 'div.flex').each(function(elm){
		                elm.remove();
		            });
		            element.addClassName('no-display');
		            element.addClassName('ignore-validate');
		            element.hide();
		        }
		    },
		    bindRemoveButtons : function(){
		        var buttons = $$('tbody#link_items_body .delete-link-item');
		        for(var i=0;i<buttons.length;i++){
		            if(!$(buttons[i]).binded && !$(buttons[i]).hasClassName('disabled')){
		                $(buttons[i]).binded = true;
		                Event.observe(buttons[i], 'click', this.remove.bind(this));
		            }
		        }
		    }
		    
		};



	priceItems.bindRemoveButtons();
	<?php foreach ($this->getValues() as $item):?>

	var trans = {
			<?php foreach (Mage::helper('bookmepro')->getProfileTranslations($item['profile_id']) as $key => $value):?>
			<?php echo $key ?> : "<?php echo str_replace("\"", "\'", $value)?>",
			<?php endforeach;?> 	
			not: "not"
	};
	
	profileItems.add(
				"<?php echo $item['profile_id']?>",
				 "<?php echo str_replace("\"", "\'", $item['name']) ?>",
				  "<?php echo $item['amount'] ?>",
				  "<?php echo $item['amount_type'] ?>",
				  "<?php echo $item['move'] ?>",
				  trans);
	<?php endforeach;?>
// ]]></script>
	</td>
</tr>