<?php if($this->hasOptimalProfiles()): ?>

<table class="data-table" id="my-orders-table">
    <colgroup>
        <col width="1">
        <col>
        <col width="1">
        <col width="1">
        <col width="1">
        <col>
    </colgroup><thead>
        <tr class="first last">
            <th><?php echo $this->__('Card Alias') ?></th>
            <th><?php echo $this->__('Number') ?></th>
            <th><?php echo $this->__('Exp. Date') ?></th>
            <th><?php echo $this->__('Cardholder Name') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->profiles as $profile): ?>
            <tr class="odd">
                <td><?php echo $profile->getCardNickname(); ?></td>
                <td>**** **** **** <?php echo $profile->getLastFourDigits(); ?></td>
                <td><span class="nobr"><?php echo $profile->getCardExpiration(); ?></span></td>
                <td><?php echo $profile->getCardHolder(); ?></td>
                <td>
                    <button type="button" title="Delete" class="button" onclick='window.location="<?php echo Mage::getUrl('customer/optimal/delete') . 'profile_id/' . $profile->getId(); ?>";'><span><span>Delete</span></span></button>
                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>
</table>

<?php endif; ?>