<?php if ($this->getCollection()->getSize()): ?>
    <div class="toolbar">
        <ul style="width:100%">
            <div class="paging">
                <span> <?php echo $this->__('%s Product(s)', $this->getTotalNum()) ?></span> 
                <div class="pagination"><?php echo $this->getPagerHtml() ?></div>
            </div>
            <div class="sorting">
                <li style="float:right;">
                    <p><?php echo $this->__('Show') ?></p>
                    <select onchange="setLocation(this.value)" class="ui-corner-all">
                        <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
                            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if ($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                                <?php echo $_limit ?>
                            </option>
                        <?php endforeach; ?>
                    </select> <?php echo $this->__('per page') ?>
                </li>

                

                <?php if ($this->isExpanded()): ?>
                    <li style="float:right;">
                        <p><?php echo $this->__('Sort By') ?></p>
                        <select onchange="setLocation(this.value)" class="ui-corner-all">
                            <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
                                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->__($_order) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <?php /* if($this->getCurrentDirection() == 'desc'): ?>
                          <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
                          <?php else: ?>
                          <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
                          <?php endif; */ ?>
                    </li>
                <?php endif; ?>
            </div>
        </ul>
    </div>
<?php endif ?>
